In [1]:
import networkx as nx
import pandas as pd
import pygraphviz as pgv
import numpy as np
from node2vec import Node2Vec

from rdkit import Chem
from rdkit.Chem import AllChem


In [2]:
ecfp = np.load('./dataset_hard/cv_'+str(0)+'/train_fingerprint.npy')
ecfp = np.asarray(ecfp, dtype='float32').reshape(-1,1024)
print(ecfp.shape)
print(ecfp)

(14196, 1024)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [3]:
graph_source = pd.read_csv('to_graph.csv')
df = pd.read_csv('final_result_mibig.csv')

In [4]:
compound_smiles = df['chem_struct']
print(' number of no SMILES compounds', compound_smiles.isnull().sum())

 number of no SMILES compounds 764


In [5]:
# compound_smiles
#len(compound_smiles)
#
# compound_smiles[2688] is None
compound_smiles_np = compound_smiles.to_numpy()
compound_smiles_np[-1]



nan

In [19]:
import pickle
EC50 = np.loadtxt('./SMILES.txt', dtype=str, comments=None)
EC50_1 = np.loadtxt('././test_smile', dtype=str, comments=None)

In [20]:

EC50.shape
print(EC50[3])
print(EC50_1[3])
EC50 == EC50_1

CC1=C(C=CC(=C1Cl)C#N)N2CC3C(C2=O)CCC3O
CC1=C(C=CC(=C1Cl)C#N)N2CC3C(C2=O)CCC3O


array([ True,  True,  True, ...,  True,  True,  True])

In [21]:
for m in EC50:
    m = str(m)
mols_bacpi = []

for m in EC50:
    try:
        mols_bacpi.append(Chem.MolFromSmiles(m))
    except TypeError:
        continue
fp_bacpi = []
for mol in mols_bacpi:
    morganfp_bacpi = AllChem.GetMorganFingerprintAsBitVect(mol,2,nBits=1024)
    fp_bacpi.append(morganfp_bacpi)
fp_bacpi =np.array(fp_bacpi, dtype='float32')
fp_bacpi.shape

(11483, 1024)

In [22]:
np.save('./ecfp_compounds_bacpi.npy', fp_bacpi)

In [9]:
mols = []

for m in compound_smiles_np:
    try:
        mols.append(Chem.MolFromSmiles(m))
    except TypeError:
        continue
# smi = Chem.SmilesMolSupplier(compound_smiles[0],delimiter='\t',titleLine=False)

# mols = [mol for mol in smi if mol is not None]
fp = []

for mol in mols:
    morganfp = AllChem.GetMorganFingerprintAsBitVect(mol,2,nBits=1024)
    fp.append(morganfp)
fp = np.array(fp, dtype='float32')

[18:57:14] Conflicting single bond directions around double bond at index 26.
[18:57:14]   BondStereo set to STEREONONE and single bond directions set to NONE.
[18:57:15] WARNING: not removing hydrogen atom without neighbors
[18:57:15] WARNING: not removing hydrogen atom without neighbors
[18:57:15] WARNING: not removing hydrogen atom without neighbors
[18:57:15] WARNING: not removing hydrogen atom without neighbors
[18:57:15] WARNING: not removing hydrogen atom without neighbors
[18:57:15] WARNING: not removing hydrogen atom without neighbors
[18:57:15] WARNING: not removing hydrogen atom without neighbors
[18:57:15] WARNING: not removing hydrogen atom without neighbors


In [44]:
type(compound_smiles_np[0])
#type(EC50[0])

numpy.str_

In [68]:
fp.shape
np.save('./ecfp_compounds_noncomplete.npy', fp)