In [1]:
import networkx as nx
import pandas as pd
import pygraphviz as pgv
import numpy as np
from node2vec import Node2Vec



In [3]:
ecfp = np.load('./dataset_hard/cv_'+str(0)+'/train_fingerprint.npy')
ecfp = np.asarray(ecfp, dtype='float32').reshape(-1,1024)
print(ecfp.shape)
print(ecfp)

(14196, 1024)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [4]:
graph_source = pd.read_csv('to_graph.csv')
df = pd.read_csv('final_result_mibig.csv')

In [52]:
compound_smiles = df['chem_struct']
print(' number of no SMILES compounds', compound_smiles.isnull().sum())

 number of no SMILES compounds 764


In [60]:
# compound_smiles
#len(compound_smiles)
#
# compound_smiles[2688] is None
compound_smiles_np = compound_smiles.to_numpy()
compound_smiles_np[-1]



nan

In [62]:
from rdkit import Chem
from rdkit.Chem import AllChem
mols = []

for m in compound_smiles_np:
    try:
        mols.append(Chem.MolFromSmiles(m))
    except TypeError:
        continue
# smi = Chem.SmilesMolSupplier(compound_smiles[0],delimiter='\t',titleLine=False)

# mols = [mol for mol in smi if mol is not None]
fp = []

for mol in mols:
    morganfp = AllChem.GetMorganFingerprintAsBitVect(mol,2,nBits=1024)
    fp.append(morganfp)
fp = np.array(fp, dtype='float32')



[17:04:05] Conflicting single bond directions around double bond at index 26.
[17:04:05]   BondStereo set to STEREONONE and single bond directions set to NONE.
[17:04:05] WARNING: not removing hydrogen atom without neighbors
[17:04:05] WARNING: not removing hydrogen atom without neighbors
[17:04:05] WARNING: not removing hydrogen atom without neighbors
[17:04:05] WARNING: not removing hydrogen atom without neighbors
[17:04:05] WARNING: not removing hydrogen atom without neighbors
[17:04:05] WARNING: not removing hydrogen atom without neighbors
[17:04:05] WARNING: not removing hydrogen atom without neighbors
[17:04:05] WARNING: not removing hydrogen atom without neighbors


In [68]:
fp.shape
np.save('./ecfp_compounds_noncomplete.npy', fp)