In [1]:
import numpy as np

ecfp = np.load('./dataset_hard/cv_'+str(0)+'/train_fingerprint.npy')
ecfp = np.asarray(ecfp, dtype='float32').reshape(-1,1024)

In [3]:
print(ecfp.shape)
print(ecfp)

(14196, 1024)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
